[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "dallen-flask"
description = "Basic Flask backend for dallen.co"
repository = "git@github.com:damienallen/dallen.git"
version = "2.1"
authors = ["Damien Allen <dev@dallen.co>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
flask-wtf = "^0.14.3"
gunicorn = "^20.0.4"
sendgrid = "^6.3.1"
email_validator = "^1.1.1"
requests = "^2.23.0"

[tool.poetry.dev-dependencies]
flake8 = "^3.8.2"
black = "^19.10b0"
